# Generated by Django 6.0.1 on 2026-08-17 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_orderitem_order_vendororder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vendor_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_vendors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor_status',
            field=models.CharField(choices=[('not_vendor', 'Not a Vendor'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='not_vendor', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vendor_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
